import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:denik_zza/main.dart' as app;
import 'package:denik_zza/database/database_wrapper.dart';
import '../infrastructure/robots/base_robot.dart';
import 'package:denik_zza/utils/mode_coordinator.dart';
import 'package:denik_zza/utils/app_logger.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  // Simple sanity check: Does the app launch and show the main screen?
  // No complex seeding, just pure launch.
  testWidgets('Sanity Check: App Launches and Shows Home Screen',
      (tester) async {
    // 1. Setup: Use Integration mode (file-based DB in isolated folder)
    // Note: runId is auto-generated by ModeCoordinator on first call per process
    await ModeCoordinator.setIntegrationTestMode(testName: 'sanity_check');
    AppLogger.l.d(
        'Sanity Check: Mode set - ${ModeCoordinator.currentRunId}/sanity_check');

    // 2. Ensure DB is ready (even if empty)
    AppLogger.l.d('Calling DatabaseWrapper.getDatabase()');
    try {
      DatabaseWrapper.getDatabase();
      AppLogger.l.d('DB Initialized');
    } catch (e) {
      AppLogger.l.e('DB Init Failed: $e');
      rethrow;
    }

    // 3. Launch app
    AppLogger.l.d('Calling app.main()');
    try {
      app.main();
      AppLogger.l.d('App Main Called');
    } catch (e) {
      AppLogger.l.e('App Main Failed: $e');
      rethrow;
    }

    AppLogger.l.d('Pumping frames after launch');
    await tester.pump();
    final robot = BaseRobot(tester);
    // Wait for app to be ready - pumpAndSettle waits for animations/microtasks
    final addButtonKey = find.byKey(const Key('EventList_add_button'));
    await robot.pumpAndSettle();
    if (addButtonKey.evaluate().isEmpty) {
      throw TestFailure('App did not launch - EventList_add_button not found after 5s');
    }
    AppLogger.l.d('App Pumped');

    // 4. Verify Title "Všechny akce"
    AppLogger.l.d('Checking for Title');
    expect(find.text('Všechny akce'), findsOneWidget);
    AppLogger.l.d('Title Found');

    // 5. Verify we are at least on a screen with a Scaffold
    AppLogger.l.d('Checking for ListView');
    expect(find.byType(ListView), findsOneWidget); // EventList uses ListView
    AppLogger.l.d('Sanity Check Complete');
  });
}
