import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:denik_zza/main.dart' as app;
import 'package:denik_zza/database/database_wrapper.dart';
import 'package:denik_zza/database/drift_database_connector.dart';
import 'package:denik_zza/utils/mode_coordinator.dart';
import 'package:denik_zza/utils/app_logger.dart';

import '../../infrastructure/data/simulation_profiles.dart';
import '../../infrastructure/robots/dashboard_robot.dart';
import '../../infrastructure/robots/event_detail_robot.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  // Set frame policy for better stability in integration tests
  IntegrationTestWidgetsFlutterBinding.instance.framePolicy =
      LiveTestWidgetsFlutterBindingFramePolicy.fullyLive;

  // Strict analysis check: 0 issues.
  group('E2E Tier 1: Canary Test (Jurský Park)', () {
    testWidgets('Verify Core Flow: Seed -> Dashboard -> Event -> Intake',
        (tester) async {
      // 1. Setup: Use Integration Test mode (file-based DB for debugging)
      // Integration tests use persistent DB for inspection after failures.
      // Note: runId is auto-generated by ModeCoordinator on first call per process
      await ModeCoordinator.setIntegrationTestMode(testName: 'jursky_park_e2e');
      AppLogger.l.d(
          'Integration test mode set - ${ModeCoordinator.currentRunId}/jursky_park_e2e');

      // 2. Database & Seeding
      AppLogger.l.d('Seeding Database');
      final connector = DatabaseWrapper.getDatabase() as DriftDatabaseConnector;
      await seedDatabase(connector.appDatabase, SimulationProfile.standard());

      // 3. Launch App
      AppLogger.l.d('Launching App');
      app.main(); // Don't await - main() returns void (fires async work internally)
      await tester.pump(); // Schedule first frame
      await tester.pumpAndSettle(); //Wait for all animations

      // 4. Robot Initialization
      final dashboard = DashboardRobot(tester);
      final eventDetail = EventDetailRobot(tester);

      // 5. Verify Dashboard
      AppLogger.l.d('Verifying Dashboard Page');
      await dashboard.verifyPageShown();
      AppLogger.l.d('Verifying Jurský Park event');
      await dashboard.verifyEventPresent('Jurský Park');

      // 6. Navigate to Event
      AppLogger.l.d('Tapping Jurský Park');
      await dashboard.tapEvent('Jurský Park');

      // 7. Verify Event Detail
      AppLogger.l.d('Verifying Event Detail Page');
      await eventDetail.verifyPageShown();
      AppLogger.l.d('Verifying Participant Karel Čapek');
      await eventDetail.verifyParticipantPresent('Karel Čapek');

      // 8. Navigate to Participant Detail
      AppLogger.l.d('Tapping Karel Čapek');
      await eventDetail.tapParticipant('Karel Čapek');

      // 9. Verify Participant Detail (Basic check)
      AppLogger.l.d('Verifying Participant Detail Page');
      await tester.pumpAndSettle();
      expect(find.text('Karel Čapek'), findsOneWidget); // Header
      expect(find.text('Informace o účastníkovi'), findsOneWidget);
    });
  });
}
